name: "Podcast Generator"
author: "Siyamthanda Ndlovu"
description: "Generates podcast feed from a YAML file"
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "git-branch"
  color: "orange"
inputs:
  email:
    description: The email address of the commiter
    required: true
    default: ${{github.actor}}@localhost
  name:
    description: The committer's name
    required: true
    defaul: ${{ github.actor }}